[package]
name = "top_level"
version = "0.1.0"
edition = "2024"

[workspace]
members = [ "src/greet",
    "src/authentication",
    "src/console_input",
    "src/greet",
    "src/hello_world",
    "src/login",
    "src/login_manager",
]
