[package]
name = "login_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
authentication = { version = "0.1.0", path = "../authentication" }
clap = { version = "4.5.38", features = ["derive"] }
